#!/bin/bash

# Task 2B Quick Start Script
# This script helps you run Task 2B detection and manipulation

echo "=========================================="
echo "Task 2B Quick Start"
echo "=========================================="
echo ""
echo "You need TWO terminals to run Task 2B:"
echo ""
echo "Terminal 1 - Detection Node:"
echo "  cd ~/colcon_ws"
echo "  source install/setup.bash"
echo "  ros2 run ur5_control task2b_detection.py"
echo ""
echo "Terminal 2 - Manipulation Node:"
echo "  cd ~/colcon_ws"
echo "  source install/setup.bash"
echo "  ros2 run ur5_control task2b_manipulation.py"
echo ""
echo "=========================================="
echo "Expected Sequence:"
echo "=========================================="
echo "1. Detection node publishes TF transforms"
echo "2. Manipulation waits 3 seconds for detection to stabilize"
echo "3. Manipulation moves to HOME position"
echo "4. Scans for objects via TF"
echo "5. Starts pick-and-place (fertilizer first, then fruits)"
echo ""
echo "=========================================="
echo "Troubleshooting:"
echo "=========================================="
echo "- If 'No objects detected': Detection node not running or no fruits/fertilizer in view"
echo "- If stuck at INIT: Wait 3 seconds for countdown"
echo "- If joint limits: Check waypoint positions in code"
echo ""
