#!/bin/bash

# Task 2B Quick Reference Script
# This script provides commands to run Task 2B

echo "=========================================="
echo "  Task 2B: Pick and Place Quick Guide"
echo "=========================================="
echo ""
echo "Team ID: 2203"
echo ""
echo "STEP 1: Configure Link Attacher Plugin (One-time setup)"
echo "----------------------------------------"
echo "Run this command ONCE:"
echo "  echo 'export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=/home/kasinath/colcon_ws/src:\$IGN_GAZEBO_SYSTEM_PLUGIN_PATH' >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""
echo "Verify with:"
echo "  echo \$IGN_GAZEBO_SYSTEM_PLUGIN_PATH"
echo ""
echo ""
echo "STEP 2: Build Package"
echo "----------------------------------------"
echo "  cd ~/colcon_ws"
echo "  colcon build --packages-select ur5_control"
echo "  source install/setup.bash"
echo ""
echo ""
echo "STEP 3: Run Task 2B (Open 4 Terminals)"
echo "----------------------------------------"
echo ""
echo "Terminal 1 - Launch Gazebo World:"
echo "  source ~/colcon_ws/install/setup.bash"
echo "  ros2 launch eyantra_warehouse task2b.launch.py"
echo ""
echo "Terminal 2 - Spawn UR5 Arm:"
echo "  source ~/colcon_ws/install/setup.bash"
echo "  ros2 launch ur_simulation_gz spawn_arm.launch.py"
echo ""
echo "Terminal 3 - Run Detection Script:"
echo "  source ~/colcon_ws/install/setup.bash"
echo "  ros2 run ur5_control task2b_detection.py"
echo ""
echo "Terminal 4 - Run Manipulation Script:"
echo "  source ~/colcon_ws/install/setup.bash"
echo "  ros2 run ur5_control task2b_manipulation.py"
echo ""
echo ""
echo "=========================================="
echo "  What Each Script Does"
echo "=========================================="
echo ""
echo "Detection Script (task2b_detection.py):"
echo "  • Detects bad fruits (Task 1B method)"
echo "  • Detects fertilizer cans with ArUco markers (Bonus Task 2 method)"
echo "  • Publishes TF transforms for all detected objects"
echo ""
echo "Manipulation Script (task2b_manipulation.py):"
echo "  • Scans for objects (waits 3 seconds)"
echo "  • Picks up bad fruits → places in trashbin"
echo "  • Picks up fertilizer → places on eBot top"
echo "  • Uses magnetic gripper (link attacher service)"
echo "  • Returns to home after each object"
echo ""
echo ""
echo "=========================================="
echo "  Gripper Service Commands (Manual)"
echo "=========================================="
echo ""
echo "Attach Bad Fruit:"
echo "  ros2 service call /attach_link linkattacher_msgs/srv/AttachLink \\"
echo "    \"{model1_name: 'bad_fruit', link1_name: 'body', model2_name: 'ur5', link2_name: 'wrist_3_link'}\""
echo ""
echo "Detach Bad Fruit:"
echo "  ros2 service call /detach_link linkattacher_msgs/srv/DetachLink \\"
echo "    \"{model1_name: 'bad_fruit', link1_name: 'body', model2_name: 'ur5', link2_name: 'wrist_3_link'}\""
echo ""
echo "Attach Fertilizer:"
echo "  ros2 service call /attach_link linkattacher_msgs/srv/AttachLink \\"
echo "    \"{model1_name: 'fertiliser_can', link1_name: 'body', model2_name: 'ur5', link2_name: 'wrist_3_link'}\""
echo ""
echo "Detach Fertilizer:"
echo "  ros2 service call /detach_link linkattacher_msgs/srv/DetachLink \\"
echo "    \"{model1_name: 'fertiliser_can', link1_name: 'body', model2_name: 'ur5', link2_name: 'wrist_3_link'}\""
echo ""
echo ""
echo "=========================================="
echo "  Debugging Commands"
echo "=========================================="
echo ""
echo "Check if objects detected:"
echo "  ros2 run tf2_ros tf2_echo base_link 2203_bad_fruit_1"
echo "  ros2 run tf2_ros tf2_echo base_link 2203_fertilizer_0_base"
echo ""
echo "List all TF frames:"
echo "  ros2 run tf2_ros tf2_echo --list"
echo ""
echo "Check gripper services:"
echo "  ros2 service list | grep attach"
echo ""
echo "Monitor arm movement:"
echo "  ros2 topic echo /delta_twist_cmds"
echo ""
echo "View TF tree:"
echo "  ros2 run rqt_tf_tree rqt_tf_tree"
echo ""
echo ""
echo "For detailed README, see:"
echo "  ~/colcon_ws/src/ur5_control/TASK2B_README.md"
echo ""
